name: Build

on: [push, pull_request]

jobs:
  osx-build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_build: [cp311-macosx_arm64]
        os: [macos-14]
    env:
      CIBW_BEFORE_ALL: 'uname -a'
      CIBW_ARCHS: 'auto'
      CIBW_BUILD: ${{ matrix.python_build }}      

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        with:
          package-dir: quickfix-python

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.python_build }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl