name: Build

on: [push, pull_request]

jobs:
  osx-build-wheels:
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_build: [cp311-macosx_arm64]        
        os: [macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_BEFORE_ALL: 'uname -a'
          CIBW_BUILD: ${{ matrix.python_build }}
          CIBW_ARCHS: auto
        with:
          package-dir: quickfix-python

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.python_build }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl