name: Build

on: [push, pull_request]

jobs:
  build-wheels-linux:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_build: [cp311-manylinux_aarch64, cp312-manylinux_aarch64]  # Added cp312 for Python 3.12
        os: [ubuntu-latest]
    env:
      CIBW_ARCHS: aarch64
      CIBW_BUILD: ${{ matrix.python_build }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Changed from 3.11 to 3.12

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        with:
          package-dir: quickfix-py
        env:
          CIBW_BEFORE_ALL_LINUX: 'uname -a && ls -la && ./setup-linux-yum.sh'
          CIBW_BUILD: ${{ matrix.python_build }}

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.python_build }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build-wheels-osx:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_build: [cp311-macosx_arm64, cp312-macosx_arm64]  # Added cp312 for Python 3.12
        os: [macos-14]
    env:
      CIBW_ARCHS: 'auto'
      CIBW_BUILD: ${{ matrix.python_build }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Changed from 3.11 to 3.12

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        with:
          package-dir: quickfix-py

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.python_build }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build-wheels-windows:
    name: Build wheels on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python_build: [cp311-win_amd64, cp312-win_amd64]  # Added cp312 for Python 3.12
    env:
      CIBW_BUILD: ${{ matrix.python_build }}
      CIBW_ENVIRONMENT: "CXXFLAGS='-std=c++17'"  # Enforces C++17

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Build Tools
        run: |
          choco install visualstudio2019buildtools
          choco install visualstudio2019-workload-vctools

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        with:
          package-dir: quickfix-py

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.python_build }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Build sdist
        run: pipx run build --sdist --outdir dist quickfix-py

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_all:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # Only publish to PyPI on tag pushes
    needs: [build-wheels-linux, build-wheels-osx, build-wheels-windows, make_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/quickfix-py
    permissions:
      id-token: write
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
